[project]
name = "user"
version = "0.1.0"
description = "User API Endpoints"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.85",
    "shared",
    "types-boto3[cognito-idp]>=1.42.85",
]

[tool.uv.sources]
shared = { workspace = true }

[build-system]
requires = ["uv_build>=0.8.0,<0.9"]
build-backend = "uv_build"