[project]
name = "companies"
version = "0.3.0"
description = "Company API Endpoints"
requires-python = ">=3.12"
dependencies = [
    "pydantic-extra-types[phonenumbers]>=2.11.1",
    "pydantic[email]>=2.12.5",
    "shared",
]

[tool.uv.sources]
shared = { workspace = true }

[build-system]
requires = ["uv_build>=0.8.0,<0.9"]
build-backend = "uv_build"
