[project]
name = "k9-api"
version = "0.1.0"
readme = "README.md"
authors = [
    { name = "Rodriguez, Santiago", email = "srodvasquez@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aws-lambda-powertools>=3.26.0",
    "boto3>=1.42.85",
    "shared",
]

[tool.uv]
package = false

[tool.uv.workspace]
members = [
    "shared",
    "services/*",
]

[tool.uv.sources]
shared = { workspace = true }

[dependency-groups]
dev = [
    "ruff>=0.15.8",
]
